### PR TITLE
Start notebook for persistence landscapes

### PR DESCRIPTION
**Pull request by calderds**
Add axis passthrough for simple plotting functions a la persim/visuals.py

### CODE REVIEW

**Review by catanzaromj — COMMENTED** [review]
Looks great except for one issue. When I run

```python
plot_landscape(true_diff_pl,title='Difference of average PLs')
```
I get the error
```python
TypeError: plot_landscape_approx() got an unexpected keyword argument 'ax'
```

**Comment by calderds** [comment]
Fixed this bug in latest commit. Should work for you now!

**Comment by catanzaromj** [comment]
Awesome. I'm about to push another notebook that is quite similar to yours. Would you mind if we took yours in another direction? I noticed you wanted some edits made to it anyways.

**Comment by calderds** [comment]
Sure. I'll merge the two branches, and you can commit your notebook with a different name. I'm interested to take a look at it and see what the best direction is for my notebook.

**Pull request merged**
